First project's part
sergio-usma/Portfolio pull request #1
Opened 2023-03-24 23:05 UTC by sergio-usma

- The linter has been set up correctly for this repository, resulting in no errors.
- All the linters result in green and there are no custom changes to linter config.
- GitHub Flow has been used correctly with a descriptive README file, meaningful commit messages, and Pull Requests that have a descriptive title and short summary of the changes introduced.
- Work has been documented in a professional way, using a logo and having into account the recommendations from past assignments.
- Pull Request was made from a feature branch.

2023-03-24 23:44 UTC, Shedrack-Sunday requested changes
Hi @sergio-usma  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have the `future features` section of the README filed up

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 01:18 UTC, sergio-usma commented
> Hi @sergio-usma
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request 
> You have submitted a project, that does not have the `future features` section of the README filed up
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hi Shedrack, thanks for your feedback. I have made the changes, however, the requirements of the activity were the next:
https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md
So, I didn't know the "Future features" part of the README.md was a cause for don't pass the activity. So thank you for letting me know!

2023-03-25 18:21 UTC, amon-cofie requested changes
Hi @sergio-usma , 

Good job so far! You evidently put a lot of work into this. 💪 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
🚀 No linter errors
🚀 Descriptive pull request
🚀 Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 18:21 UTC, amon-cofie commented on index.html
> +    </nav>
This is great work. Great use of the nav tag which makes your code semantically sound. To improve upon the semantics, however, you can enclose the nav in a ```header``` tag as well. Find out more about this [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) 👍

2023-03-25 18:21 UTC, amon-cofie commented on index.html
> +      <img src="./media/image_geometry_1.png" alt="" srcset="" />
Really nice work on this area but while this works in making the page look like the figma design template, I would suggest that you use a css background image property to place this image as it only adds aesthetics to your page but is not actually part of the main content of the page. This will improve your SEO score. You can check out [this stack overflow thread](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) to find out more 👍

2023-03-25 18:21 UTC, amon-cofie commented on index.html
> +        </div>
As for the earlier comment, please consider using a CSS background property instead of adding the image in your HTML as it only adds aesthetics and is not actually part of the main content of the page 👍

2023-03-25 21:25 UTC, sergio-usma commented on index.html
> +    </nav>
Done! Thanks for the feedback.

2023-03-25 21:26 UTC, sergio-usma commented on index.html
> +      <img src="./media/image_geometry_1.png" alt="" srcset="" />
Done!

2023-03-25 21:26 UTC, sergio-usma commented on index.html
> +        </div>
Done!

2023-03-25 21:34 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @sergio-usma , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... great design
✅ ... green linters

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 22:13 UTC, merged