Final part
sergio-usma/Portfolio pull request #3
Opened 2023-03-31 21:45 UTC by sergio-usma

- The "About myself" section (placed after the projects and before the contact form) with content aligned using Flexbox
- CSS Grid and Flexbox have been used to lay out the elements in the "Projects" section.
- CSS Grid has been used in the main container containing all the cards, and Flexbox has been used to lay out an individual card.
- The "Projects" and "About myself" sections use ul and li for categories. HTML, CSS, and Javascript are list items for the "Projects" section, and Languages, Frameworks, and Skills are list items for the "About myself" section.
- The detail modal window that requires JavaScript has not been implemented.
- Using the templates in Figma, the design has been followed as closely as possible (e.g., font, colors, images, text, margins).
- Button interactions (hover, etc.) have been implemented.

2023-03-31 22:24 UTC, tufoinnkuo10 requested changes
Hi @sergio-usma 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-03-31 22:24 UTC, tufoinnkuo10 commented on index.html
> +          <h2>Project name goes here</h2>
- [ ] Great job.. please, there is this extra margin right on your projects and headline section making your mobile version to have a scroll from left to right. Please fix that.

![demo4](https://user-images.githubusercontent.com/65298048/229242617-a3d7fe99-00dd-434b-a1e2-197b8af4ad94.gif)

2023-03-31 22:24 UTC, tufoinnkuo10 commented on index.html
> +          I can help you build a product , feature or website Look through some
- [ ] please, kindly centralize the about section. Both the left and right margins should be the same. For now, the right is wider than the left. Please fix that.  
![Screenshot (923)_LI](https://user-images.githubusercontent.com/65298048/229243041-3ab9cf59-c779-4e3d-9663-25ccab986ccf.jpg)

2023-04-01 02:41 UTC, sergio-usma commented on index.html
> +          <h2>Project name goes here</h2>
Ok! Done!

2023-04-01 02:42 UTC, sergio-usma commented on index.html
> +          I can help you build a product , feature or website Look through some
Ok! Thank you very much for your advice. You help me to be better!

2023-04-01 03:15 UTC, amejid approved these changes
Hi @sergio-usma, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 03:18 UTC, merged